spring.application.name=BloodBank

spring.datasource.url=jdbc:mysql://localhost:3306/bloodbank
spring.datasource.username=root
spring.datasource.password=H1A2R3I4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true